name: Run npm commands

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string

      node-version:
        default: 18
        type: number

      path:
        default: "."
        type: string
      
      build-timeout:
        default: 15
        type: number

jobs:
  npm-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: ${{ inputs.path }}

      - name: Install node
        timeout-minutes: 5
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        timeout-minutes: 5
        run: |
          npm ci --no-progress

      - name: Run task
        timeout-minutes: ${{ inputs.build-timeout }}
        run: |
          ${{ inputs.run }}
