name: Run npm commands

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string

      node-version:
        default: 18
        type: number

      path:
        default: "."
        type: string
      
      build-timeout:
        default: 15
        type: number

jobs:
  npm-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: ${{ inputs.path }}

      - name: Install node
        timeout-minutes: 5
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        timeout-minutes: 5
        run: |
          npm ci --no-progress

      - name: Run task
        timeout-minutes: ${{ inputs.build-timeout }}
        run: |
          ${{ inputs.run }}
