name: Portainer deploy stack

on:
  workflow_call:

jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get latest commit hash
      id: fetch-latest-hash
      run: echo "::set-output name=latest-hash::$(git rev-parse --short $GITHUB_SHA)"

    - name: Fetch latest release version
      id: fetch-latest-release
      uses: reloc8/action-latest-release-version@1.0.0

    - name: Lowercase repo name
      id: repo-name
      run: echo "::set-output name=lowercase-name::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"

    - name: Set stack name
      id: stack-name
      run: echo "::set-output name=name::gh-$(echo '${{ steps.repo-name.outputs.lowercase-name }}' | perl -ne 's/(?<=\/)([a-zA-Z-_]+)/$1/; print $1;')"

    - name: Deploy stack to Portainer
      uses: DaniFoldi/portainer-stack-deploy@v1.3.1
      with:
        portainer-host: ${{ secrets.PORTAINER_HOST }}
        username: ci
        password: ${{ secrets.PORTAINER_KEY }}
        endpoint-id: 2
        stack-name: ${{ steps.stack-name.outputs.name }}
        stack-definition: docker-compose.yml
        variables: '{"stable": "${{ steps.fetch-latest-release.outputs.latest-release }}", "beta": "${{ steps.fetch-latest-hash.outputs.latest-hash }}"}'